# Mapnik requires GLIBCXX_3.4.21, which is not available on standard Jessie deb build for Docker node image
# so build from scratch

FROM mhart/alpine-node:8
RUN apk --no-cache add libc6-compat tini
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --production

COPY . .

EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "--max_old_space_size=300", "./build/www.js"]
